modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/extra_armor_info/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "extra_armor_info"
version = "${version}"
displayName = "Extra Armor Info"
authors = "MrMelon54, PiemanDev"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.extra_armor_info]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extra_armor_info]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extra_armor_info]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
