modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MrMelon54/extra_armor_info/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "extra_armor_info"
version = "${version}"
displayName = "Extra Armor Info"
authors = "MrMelon54, PiemanDev"
description = "Adds HUD icons for armour toughness and knockback resistance"
logoFile = "/icon.png"

[[dependencies.extra_armor_info]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extra_armor_info]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extra_armor_info]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"
